site_name: Viscope
nav:
  - Home: index.md
  - Installation: installation.md
  - Extensions: extensions.md
  - Software Architecture: architecture.md
  - Class Hierarchy: class_hierarchy.md
  - Examples: examples.md
theme: readthedocs

hooks:
  - docs/hooks.py

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            merge_init_into_class: true